2020-01-29 01:34:47.268 DEBUG main - <module>: This message should go to the log file
2020-01-29 01:50:30.736 DEBUG main - <module>: Iniciando Servicio
2020-01-29 01:51:30.115 DEBUG main - <module>: Iniciando Servicio
2020-01-29 01:51:30.119 DEBUG main - main: Conecrado al broker
2020-01-29 02:46:14.899 DEBUG main - <module>: Iniciando Servicio
2020-01-29 02:46:15.020 DEBUG main - main: Conectano al broker
2020-01-29 02:48:52.612 DEBUG main - <module>: Iniciando Servicio
2020-01-29 02:48:52.630 INFO _internal - _log:  * Running on http://localhost:5000/ (Press CTRL+C to quit)
2020-01-29 02:50:09.497 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 02:50:09] "GET / HTTP/1.1" 200 -
2020-01-29 02:50:10.239 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 02:50:10] "GET /favicon.ico HTTP/1.1" 404 -
2020-01-29 02:51:36.132 DEBUG main - main: Conectano al broker
2020-01-29 03:35:36.243 DEBUG main - <module>: Iniciando Servicio
2020-01-29 03:35:36.253 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-01-29 03:35:45.194 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 03:35:45] "GET / HTTP/1.1" 200 -
2020-01-29 03:35:45.704 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 03:35:45] "GET /favicon.ico HTTP/1.1" 404 -
2020-01-29 04:19:07.137 DEBUG main - main: Conectano al broker
2020-02-01 02:49:47.931 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:49:48.004 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:52:42.314 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:52:42.337 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:53:42.681 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:53:42.712 DEBUG main - main: Conectano al broker
2020-02-01 02:53:42.720 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:55:23.916 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:55:23.940 DEBUG main - main: Conectano al broker
2020-02-01 02:55:23.943 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:56:14.080 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:56:14.090 DEBUG main - main: Conectando al broker
2020-02-01 02:56:14.091 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:57:12.109 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:57:12.128 DEBUG main - main: Conectando al broker
2020-02-01 02:57:12.131 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:04:25.478 DEBUG main - <module>: Iniciando Servicio
2020-02-01 03:04:25.501 DEBUG main - main: Conectando al broker
2020-02-01 03:04:25.504 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:39.178 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:39.598 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:41.523 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:41.798 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:42.073 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:42.442 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:06:27.368 DEBUG main - <module>: Iniciando Servicio
2020-02-01 03:06:27.389 DEBUG main - main: Conectando al broker
2020-02-01 03:06:42.453 DEBUG main - <module>: Iniciando Servicio
2020-02-01 03:06:42.465 DEBUG main - main: Conectando al broker
2020-02-01 03:06:42.491 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:06:52.847 DEBUG main - on_message: Incoming message!
2020-02-01 06:05:56.869 DEBUG main - <module>: Iniciando Servicio
2020-02-01 06:06:38.406 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:56:50.978 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:58:39.210 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:59:23.517 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:59:36.017 DEBUG main - <module>: Iniciando Servicio
2020-02-01 20:56:26.807 DEBUG main - <module>: Iniciando Servicio
2020-02-01 20:57:36.041 DEBUG main - <module>: Iniciando Servicio
2020-02-01 20:59:54.401 DEBUG main - <module>: Iniciando Servicio
2020-02-01 21:00:46.200 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:42:45.556 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:43:02.284 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:43:24.727 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:44:35.875 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:52:28.094 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:53:19.821 DEBUG main - <module>: Iniciando Servicio
2020-02-01 23:58:24.239 DEBUG main - <module>: Iniciando Servicio
2020-02-01 23:59:11.047 DEBUG main - <module>: Iniciando Servicio
2020-02-01 23:59:25.720 DEBUG main - <module>: Iniciando Servicio
2020-02-02 00:39:22.383 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:14:55.626 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:17:14.261 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:17:47.126 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:18:32.720 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:19:23.765 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:19:45.648 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:21:58.573 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:22:31.729 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:22:51.053 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:35:11.734 DEBUG main - <module>: Iniciando Servicio
2020-02-02 06:39:23.133 DEBUG main - <module>: Iniciando Servicio
2020-02-02 06:40:00.165 DEBUG main - <module>: Iniciando Servicio
2020-02-02 06:40:00.259 DEBUG main - main: Conectando al broker
2020-02-02 06:40:00.266 INFO _internal - _log:  * Running on http://localhost:8080/ (Press CTRL+C to quit)
2020-02-02 06:44:57.128 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 06:44:57.323 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 06:44:57] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 17:22:27.263 DEBUG main - <module>: Iniciando Servicio
2020-02-02 17:22:27.461 DEBUG main - main: Conectando al broker
2020-02-02 17:22:27.478 INFO _internal - _log:  * Running on http://localhost:8080/ (Press CTRL+C to quit)
2020-02-02 17:24:08.379 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 17:24:08.435 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 17:24:08] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:35:25.523 DEBUG main - <module>: Iniciando Servicio
2020-02-02 22:35:25.712 DEBUG main - main: Conectando al broker
2020-02-02 22:35:25.724 INFO _internal - _log:  * Running on http://localhost:8080/ (Press CTRL+C to quit)
2020-02-02 22:35:37.799 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:35:37.873 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:35:37] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:36:33.920 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:36:33.923 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:36:33] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:37:11.414 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:37:11.419 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:37:11] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:37:23.927 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:37:23.936 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:37:23] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:38:41.310 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:38:41.315 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:38:41] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:43:15.713 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:43:15.721 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:43:15] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:44:25.134 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:44:25.140 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:44:25] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:45:18.067 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:45:18.072 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:45:18] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:52:47.926 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:52:47.929 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:52:47] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:52:54.934 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:52:54.942 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:52:54] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:14:47.694 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:14:47.706 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:14:47] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:15:01.763 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:15:01.767 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:15:01] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:20:31.346 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:20:31.353 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:20:31] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:20:38.005 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:20:38.012 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:20:38] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:20:55.850 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:20:55.863 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:20:55] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:03:31.817 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:03:31.820 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:03:31] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:05:41.804 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:05:41.810 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:05:41] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:17:26.572 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:17:26.575 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:17:26] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:17:39.385 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:17:39.390 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:17:39] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:20:46.265 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:20:46.268 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:20:46] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:21:00.000 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:21:00.044 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:21:00] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:21:11.190 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:21:11.193 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:21:11] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:30:41.897 DEBUG main - <module>: Iniciando Servicio
2020-02-03 02:30:42.084 DEBUG main - main: Conectando al broker
2020-02-03 02:30:42.394 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-03 02:30:51.415 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:30:51.441 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:30:51] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:31:55.199 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:31:55.205 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:31:55] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:32:06.597 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:32:06.602 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:32:06] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:32:34.342 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:32:34.358 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:32:34] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:33:39.225 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:33:39.232 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:33:39] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:33:53.545 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:33:53.554 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:33:53] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:34:10.592 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:34:10.602 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:34:10] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:46:36.832 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:46:36.835 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:46:36] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 16:58:19.319 DEBUG main - <module>: Iniciando Servicio
2020-02-03 16:58:19.591 DEBUG main - main: Conectando al broker
2020-02-03 16:59:26.132 DEBUG main - <module>: Iniciando Servicio
2020-02-03 16:59:26.249 DEBUG main - main: Conectando al broker
2020-02-03 16:59:26.513 INFO _internal - _log:  * Running on http://192.168.0.9:8080/ (Press CTRL+C to quit)
2020-02-03 17:01:02.306 ERROR _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:01:02] code 400, message Bad request syntax ('\x16\x03\x01\x00\x94\x01\x00\x00\x90\x03\x03\x11~\x0e\x03\x98$$Õ\x9e¼\x12\x93\x1d«·ñ\x86+ÅnSv©Æ\x80¬ãð\x16ÃÏ[\x00\x00\x1cÀ+À,Ì©À/À0Ì¨À\tÀ')
2020-02-03 17:01:02.313 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:01:02] "   ~$$Õ¼«·ñ+ÅnSv©Æ¬ãðÃÏ[  À+À,Ì©À/À0Ì¨À	À" HTTPStatus.BAD_REQUEST -
2020-02-03 17:01:39.204 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:01:39] "POST /api/device/switch HTTP/1.1" 400 -
2020-02-03 17:02:45.835 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:02:45.866 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:02:45] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 17:02:58.600 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:02:58.616 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:02:58] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 17:03:10.130 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:03:10.149 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:03:10] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 17:05:01.919 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:05:01.944 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:05:01] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-10 22:00:47.519 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:01:14.026 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:02:29.241 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:08:07.020 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:09:00.151 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:09:41.893 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:10:44.081 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:11:29.914 DEBUG main - <module>: Iniciando Servicio
